logging:
  logLevel: debug
console:
  enabled: true
external:
  domain: local
tls:
  enabled: true
  certs:
    # Internal listeners
    default:
      secretRef:
        name: tls-external
      caEnabled: true
    # External listeners
    external:
      secretRef:
        name: tls-external
      caEnabled: true
