logging:
  logLevel: debug
console:
  enabled: false
external:
  enabled: false
  domain: local
listeners:
  kafka:
    external:
      default:
        advertisedPorts:
        - 9094
        tls:
          enabled: true
  schemaRegistry:
    external:
      default:
        tls:
          enabled: true
  http:
    external:
      default:
        advertisedPorts:
        - 8083
        tls:
          enabled: true
tls:
  enabled: false
  certs:
    default: ~
    external:
      secretRef:
        name: tls-external
      caEnabled: true
